# Generated by Django 3.1.2 on 2020-11-05 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_auto_20201105_1917'),
        ('app_en', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'default_related_name': 'app_en_Blog', 'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
        migrations.AlterModelOptions(
            name='feature',
            options={'default_related_name': 'app_en_Feature', 'verbose_name': 'Feature', 'verbose_name_plural': 'Features'},
        ),
        migrations.AlterModelOptions(
            name='homeslider',
            options={'default_related_name': 'app_en_HomeSlider', 'verbose_name': 'HomeSlider', 'verbose_name_plural': 'HomeSliders'},
        ),
        migrations.AlterModelOptions(
            name='mainpic',
            options={'default_related_name': 'app_en_MainPic', 'verbose_name': 'MainPic', 'verbose_name_plural': 'MainPics'},
        ),
        migrations.AlterModelOptions(
            name='ourteam',
            options={'default_related_name': 'app_en_OurTeam', 'verbose_name': 'OurTeam', 'verbose_name_plural': 'OurTeams'},
        ),
        migrations.AlterModelOptions(
            name='ourwork',
            options={'default_related_name': 'app_en_OurWork', 'verbose_name': 'OurWork', 'verbose_name_plural': 'OurWorks'},
        ),
        migrations.AlterModelOptions(
            name='parameter',
            options={'default_related_name': 'app_en_Parameter', 'verbose_name': 'Parameter', 'verbose_name_plural': 'Parameters'},
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'default_related_name': 'app_en_Resume', 'verbose_name': 'Resume', 'verbose_name_plural': 'Resumes'},
        ),
        migrations.AlterModelOptions(
            name='technology',
            options={'default_related_name': 'app_en_Technology', 'verbose_name': 'Technology', 'verbose_name_plural': 'Technologies'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='app_en_Blog', serialize=False, to='dashboard.blog'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='feature_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='app_en_Feature', serialize=False, to='dashboard.feature'),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='homeslider_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='app_en_HomeSlider', serialize=False, to='dashboard.homeslider'),
        ),
        migrations.AlterField(
            model_name='mainpic',
            name='mainpic_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='app_en_MainPic', serialize=False, to='dashboard.mainpic'),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='ourteam_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='app_en_OurTeam', serialize=False, to='dashboard.ourteam'),
        ),
        migrations.AlterField(
            model_name='ourwork',
            name='ourwork_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='app_en_OurWork', serialize=False, to='dashboard.ourwork'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='parameter_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='app_en_Parameter', serialize=False, to='dashboard.parameter'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='resume_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='app_en_Resume', serialize=False, to='dashboard.resume'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='technology_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='app_en_Technology', serialize=False, to='dashboard.technology'),
        ),
    ]
