from django.contrib import admin
from .models import *
# from .models import GalleryPhoto2 as GalleryPhoto
admin.site.register(Notification)
admin.site.register(ProfileCustomization)
admin.site.register(Card)
admin.site.register(Jumbotron)
admin.site.register(Icon)
admin.site.register(Technology)
# admin.site.register(Blog)
admin.site.register(FAQ)
admin.site.register(Tag)
admin.site.register(CountDownItem)
admin.site.register(Parameter)
# admin.site.register(ContactMessage)
# admin.site.register(MainPic)
admin.site.register(MetaData)
admin.site.register(Link)
# admin.site.register(OurTeam)
admin.site.register(SocialLink)
# admin.site.register(HomeSlider)
admin.site.register(Region)
# admin.site.register(Feature)
admin.site.register(Testimonial)
# admin.site.register(OurWork)
admin.site.register(OurWorkCategory)
admin.site.register(Like)
admin.site.register(Comment)
admin.site.register(GalleryPhoto)
admin.site.register(GalleryAlbum)
# admin.site.register(Resume)
admin.site.register(ResumeCategory)
admin.site.register(Document)
admin.site.register(Color)

