from phoenix2 import settings

SITE_URL=settings.SITE_URL
ADMIN_URL=SITE_URL+'admin/'
MEDIA_URL=settings.MEDIA_URL
STATIC_URL=settings.STATIC_URL
SERVER_ON_PARS=settings.SERVER_ON_PARS
SERVER_ON_HEROKU=settings.SERVER_ON_HEROKU