# Generated by Django 3.1.2 on 2020-11-04 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Color', 'verbose_name_plural': 'رنگ ها'},
        ),
        migrations.AddField(
            model_name='color',
            name='color',
            field=models.CharField(default='sdsd', max_length=50, verbose_name='کد رنگ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='color',
            name='name',
            field=models.CharField(default='sdsd', max_length=50, verbose_name='نام رنگ'),
            preserve_default=False,
        ),
    ]
