# Generated by Django 3.1.2 on 2020-11-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(choices=[('account_circle', 'account_circle'), ('add_shopping_cart', 'add_shopping_cart'), ('apartment', 'apartment'), ('alarm', 'alarm'), ('attach_file', 'attach_file'), ('attach_money', 'attach_money'), ('backup', 'backup'), ('build', 'build'), ('card_travel', 'card_travel'), ('chat', 'chat'), ('construction', 'construction'), ('dashboard', 'dashboard'), ('delete', 'delete'), ('description', 'description'), ('emoji_objects', 'emoji_objects'), ('engineering', 'engineering'), ('extension', 'extension'), ('face', 'face'), ('facebook', 'facebook'), ('favorite', 'favorite'), ('fingerprint', 'fingerprint'), ('get_app', 'get_app'), ('help_outline', 'help_outline'), ('home', 'home'), ('important_devices', 'important_devices'), ('link', 'link'), ('linked_camera', 'linked_camera'), ('local_shipping', 'local_shipping'), ('lock', 'lock'), ('mail', 'mail'), ('movie_filter', 'movie_filter'), ('network_check', 'network_check'), ('notification_important', 'notification_important'), ('palette', 'palette'), ('phone', 'phone'), ('place', 'place'), ('psychology', 'psychology'), ('publish', 'publish'), ('reply', 'reply'), ('schedule', 'schedule'), ('school', 'school'), ('send', 'send'), ('settings', 'settings'), ('share', 'share'), ('sync', 'sync'), ('traffic', 'traffic'), ('two_wheeler', 'two_wheeler'), ('verified_user', 'verified_user'), ('vpn_key', 'vpn_key'), ('weekend', 'weekend')], default='important_devices', max_length=50, verbose_name='icon'),
        ),
    ]
