# Generated by Django 3.1.2 on 2020-11-04 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20201104_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_header',
            field=models.ImageField(blank=True, null=True, upload_to='market/images/Product/Header/', verbose_name='تصویر سربرگ'),
        ),
    ]
