# Generated by Django 3.1.2 on 2020-11-04 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_product_image_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_header_origin',
            field=models.ImageField(blank=True, null=True, upload_to='market/images/Category/Header/', verbose_name='تصویر سربرگ'),
        ),
    ]
