# Generated by Django 3.1.2 on 2020-11-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_color'),
        ('market', '0005_auto_20201105_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_header_origin',
            field=models.ImageField(blank=True, null=True, upload_to='market/images/Product/Header/', verbose_name='تصویر سربرگ'),
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(blank=True, to='dashboard.GalleryPhoto', verbose_name='images'),
        ),
    ]
