# Generated by Django 3.1.2 on 2020-11-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_color'),
        ('market', '0006_auto_20201105_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(blank=True, to='dashboard.Color', verbose_name='رنگ ها'),
        ),
    ]
