# Generated by Django 3.1.2 on 2020-11-05 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_auto_20201105_1255'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Color',
        ),
    ]
