# Generated by Django 3.1.2 on 2020-11-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_delete_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('سربرگ سبد خرید', 'سربرگ سبد خرید')], max_length=50, verbose_name='جای تصویر')),
                ('image_origin', models.ImageField(blank=True, null=True, upload_to='market/images/MainPic/', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'MainPic',
                'verbose_name_plural': 'تصویر های اصلی فروشگاه',
            },
        ),
    ]
