# Generated by Django 3.1.2 on 2020-11-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_marketpic'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('SHOP_DESCRIPTION', 'SHOP_DESCRIPTION')], max_length=50, verbose_name='نام')),
                ('value', models.CharField(max_length=10000, verbose_name='مقدار')),
            ],
            options={
                'verbose_name': 'Parameter',
                'verbose_name_plural': 'پارامتر ها',
            },
        ),
        migrations.AlterField(
            model_name='marketpic',
            name='name',
            field=models.CharField(choices=[('سربرگ سبد خرید', 'سربرگ سبد خرید'), ('سربرگ فروشگاه', 'سربرگ فروشگاه')], max_length=50, verbose_name='جای تصویر'),
        ),
    ]
