# Generated by Django 3.1.2 on 2020-11-05 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0036_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.blog')),
            ],
            bases=('dashboard.blog',),
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('feature_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.feature')),
            ],
            bases=('dashboard.feature',),
        ),
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('homeslider_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.homeslider')),
            ],
            bases=('dashboard.homeslider',),
        ),
        migrations.CreateModel(
            name='MainPic',
            fields=[
                ('mainpic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.mainpic')),
            ],
            bases=('dashboard.mainpic',),
        ),
        migrations.CreateModel(
            name='OurTeam',
            fields=[
                ('ourteam_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.ourteam')),
            ],
            bases=('dashboard.ourteam',),
        ),
        migrations.CreateModel(
            name='OurWork',
            fields=[
                ('ourwork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.ourwork')),
            ],
            bases=('dashboard.ourwork',),
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('parameter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.parameter')),
            ],
            bases=('dashboard.parameter',),
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('resume_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.resume')),
            ],
            bases=('dashboard.resume',),
        ),
    ]
