# Generated by Django 3.1.2 on 2020-11-07 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='app_Blog', serialize=False, to='dashboard.blog')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
                'default_related_name': 'app_Blog',
            },
            bases=('dashboard.blog',),
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('contactmessage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='app_ContactMessage', serialize=False, to='dashboard.contactmessage')),
            ],
            options={
                'verbose_name': 'ContactMessage',
                'verbose_name_plural': 'ContactMessages',
                'default_related_name': 'app_ContactMessage',
            },
            bases=('dashboard.contactmessage',),
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('feature_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='app_Feature', serialize=False, to='dashboard.feature')),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
                'default_related_name': 'app_Feature',
            },
            bases=('dashboard.feature',),
        ),
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('homeslider_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='app_HomeSlider', serialize=False, to='dashboard.homeslider')),
            ],
            options={
                'verbose_name': 'HomeSlider',
                'verbose_name_plural': 'HomeSliders',
                'default_related_name': 'app_HomeSlider',
            },
            bases=('dashboard.homeslider',),
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('link_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='app_Link', serialize=False, to='dashboard.link')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
                'default_related_name': 'app_Link',
            },
            bases=('dashboard.link',),
        ),
        migrations.CreateModel(
            name='MainPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('آیکون سایت', 'آیکون سایت'), ('سایت', 'سایت'), ('سوالات', 'سوالات'), ('جستجو', 'جستجو'), ('ویدیو', 'ویدیو'), ('درباره ما', 'درباره ما'), ('سربرگ ارتباط با ما', 'سربرگ ارتباط با ما'), ('لودینگ', 'لودینگ'), ('لوگو', 'لوگو'), ('لوگوی بزرگ', 'لوگوی بزرگ'), ('لوگوی تیره', 'لوگوی تیره'), ('لوگوی روشن', 'لوگوی روشن'), ('سربرگ مقاله', 'سربرگ مقاله'), ('سربرگ پروژه', 'سربرگ پروژه'), ('سربرگ پیش فرض برای صفحات', 'سربرگ پیش فرض برای صفحات'), ('سربرگ درباره ما', 'سربرگ درباره ما'), ('سربرگ برچسب', 'سربرگ برچسب')], max_length=50, verbose_name='جای تصویر')),
                ('image_origin', models.ImageField(blank=True, null=True, upload_to='app/images/MainPic/', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'MainPic',
                'verbose_name_plural': 'تصویر های اصلی سایت',
            },
        ),
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('metadata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='app_MetaData', serialize=False, to='dashboard.metadata')),
            ],
            options={
                'verbose_name': 'MetaData',
                'verbose_name_plural': 'MetaDatas',
                'default_related_name': 'app_MetaData',
            },
            bases=('dashboard.metadata',),
        ),
        migrations.CreateModel(
            name='OurTeam',
            fields=[
                ('ourteam_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='app_OurTeam', serialize=False, to='dashboard.ourteam')),
            ],
            options={
                'verbose_name': 'OurTeam',
                'verbose_name_plural': 'OurTeams',
                'default_related_name': 'app_OurTeam',
            },
            bases=('dashboard.ourteam',),
        ),
        migrations.CreateModel(
            name='OurWork',
            fields=[
                ('ourwork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='app_OurWork', serialize=False, to='dashboard.ourwork')),
            ],
            options={
                'verbose_name': 'OurWork',
                'verbose_name_plural': 'OurWorks',
                'default_related_name': 'app_OurWork',
            },
            bases=('dashboard.ourwork',),
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('GOOGLE_GPS_X', 'GOOGLE_GPS_X'), ('GOOGLE_GPS_Y', 'GOOGLE_GPS_Y'), ('GOOGLE_API_KEY', 'GOOGLE_API_KEY'), ('درباره ما کامل', 'درباره ما کامل'), ('درباره ما کوتاه', 'درباره ما کوتاه'), ('عنوان درباره ما', 'عنوان درباره ما'), ('آدرس', 'آدرس'), ('واحد پول', 'واحد پول'), ('ارتباط با ما', 'ارتباط با ما'), ('پیام درخواست نامعتبر', 'پیام درخواست نامعتبر'), ('ایمیل', 'ایمیل'), ('فکس', 'فکس'), ('تگ سرچ گوگل', 'تگ سرچ گوگل'), ('موقعیت در گوگل مپ', 'موقعیت در گوگل مپ'), ('موبایل', 'موبایل'), ('رنگ زمینه منوی بالای سایت', 'رنگ زمینه منوی بالای سایت'), ('رنگ متن منوی بالای سایت', 'رنگ متن منوی بالای سایت'), ('لینک تیم ما', 'لینک تیم ما'), ('عنوان تیم ما', 'عنوان تیم ما'), ('کد پستی', 'کد پستی'), ('پیش عنوان', 'پیش عنوان'), ('شرح کوتاه', 'شرح کوتاه'), ('تلفن', 'تلفن'), ('قوانین', 'قوانین'), ('رنگ سربرگ کروم در موبایل', 'رنگ سربرگ کروم در موبایل'), ('عنوان', 'عنوان'), ('لینک', 'لینک'), ('لینک ویدیو', 'لینک ویدیو'), ('عنوان ویدیو', 'عنوان ویدیو')], max_length=50, verbose_name='نام')),
                ('value', models.CharField(max_length=10000, verbose_name='مقدار')),
            ],
            options={
                'verbose_name': 'Parameter',
                'verbose_name_plural': 'پارامتر ها',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('resume_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='app_Resume', serialize=False, to='dashboard.resume')),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resumes',
                'default_related_name': 'app_Resume',
            },
            bases=('dashboard.resume',),
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('technology_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='app_Technology', serialize=False, to='dashboard.technology')),
            ],
            options={
                'verbose_name': 'Technology',
                'verbose_name_plural': 'Technologies',
                'default_related_name': 'app_Technology',
            },
            bases=('dashboard.technology',),
        ),
    ]
