# Generated by Django 3.1.2 on 2020-11-05 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_color'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('technology_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.technology')),
            ],
            options={
                'verbose_name': 'تکنولوژی',
                'verbose_name_plural': 'تکنولوژی ها',
            },
            bases=('dashboard.technology',),
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Blog', 'verbose_name_plural': 'مقاله ها'},
        ),
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name': 'سرویس', 'verbose_name_plural': 'سرویس ها'},
        ),
        migrations.AlterModelOptions(
            name='homeslider',
            options={'verbose_name': 'اسلایدر', 'verbose_name_plural': 'اسلایدر ها'},
        ),
        migrations.AlterModelOptions(
            name='mainpic',
            options={'verbose_name': 'MainPic', 'verbose_name_plural': 'تصویر های اصلی'},
        ),
        migrations.AlterModelOptions(
            name='ourteam',
            options={'verbose_name': 'تیم ما', 'verbose_name_plural': 'اعضای تیم ما'},
        ),
        migrations.AlterModelOptions(
            name='ourwork',
            options={'verbose_name': 'پروژه', 'verbose_name_plural': 'پروژه ها'},
        ),
        migrations.AlterModelOptions(
            name='parameter',
            options={'verbose_name': 'پارامتر', 'verbose_name_plural': 'پارامتر ها'},
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'verbose_name': 'رزومه', 'verbose_name_plural': 'رزومه ها'},
        ),
    ]
