# Generated by Django 3.1.2 on 2020-10-22 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('country', models.CharField(max_length=50, verbose_name='کشور')),
                ('city', models.CharField(max_length=50, verbose_name='شهر')),
                ('salary', models.IntegerField(verbose_name='حقوق')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
