# Generated by Django 3.1.2 on 2020-10-24 00:50

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=50, verbose_name='color name')),
                ('color_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='color code')),
                ('color_class', models.CharField(blank=True, choices=[('success', 'success'), ('danger', 'danger'), ('warning', 'warning'), ('primary', 'primary'), ('secondary', 'secondary'), ('info', 'info'), ('light', 'light'), ('dark', 'dark'), ('rose', 'rose'), ('DEFAULT', 'DEFAULT'), ('UNSET', 'UNSET')], default='DEFAULT', max_length=50, null=True, verbose_name='color class')),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50, verbose_name='نام')),
                ('lname', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('subject', models.CharField(max_length=50, verbose_name='عنوان پیام')),
                ('message', models.CharField(max_length=50, verbose_name='متن پیام')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='افزوده شده در')),
            ],
            options={
                'verbose_name': 'ContactMessage',
                'verbose_name_plural': 'پیام های ارتباط با ما',
            },
        ),
        migrations.CreateModel(
            name='CountDownItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='Title')),
                ('pretitle', models.CharField(blank=True, max_length=500, null=True, verbose_name='Pre Title')),
                ('for_home', models.BooleanField(default=False, verbose_name='نمایش در صفحه اصلی')),
                ('image_origin', models.ImageField(blank=True, null=True, upload_to='dashboard/images/CountDownItem/', verbose_name='تصویر')),
                ('counter', models.IntegerField(default=100, verbose_name='شمارنده')),
                ('priority', models.IntegerField(default=100, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'CountDownItem',
                'verbose_name_plural': 'شمارنده ها',
            },
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('icon_class', models.CharField(blank=True, max_length=50, null=True, verbose_name='کلاس آیکون')),
                ('image_origin', models.ImageField(blank=True, null=True, upload_to='dashboard/images/OurService/', verbose_name='تصویر')),
                ('icon_fa', models.CharField(blank=True, max_length=50, null=True, verbose_name='آیکون فونت آسوم')),
                ('icon_material', models.CharField(blank=True, choices=[('place', 'place'), ('construction', 'construction'), ('extension', 'extension'), ('engineering', 'engineering'), ('account_circle', 'account_circle'), ('add_shopping_cart', 'add_shopping_cart'), ('apartment', 'apartment'), ('alarm', 'alarm'), ('attach_file', 'attach_file'), ('attach_money', 'attach_money'), ('backup', 'backup'), ('build', 'build'), ('chat', 'chat'), ('dashboard', 'dashboard'), ('delete', 'delete'), ('description', 'description'), ('face', 'face'), ('favorite', 'favorite'), ('get_app', 'get_app'), ('help_outline', 'help_outline'), ('home', 'home'), ('important_devices', 'important_devices'), ('link', 'link'), ('local_shipping', 'local_shipping'), ('lock', 'lock'), ('mail', 'mail'), ('notification_important', 'notification_important'), ('psychology', 'psychology'), ('publish', 'publish'), ('reply', 'reply'), ('schedule', 'schedule'), ('send', 'send'), ('settings', 'settings'), ('share', 'share'), ('sync', 'sync'), ('vpn_key', 'vpn_key')], max_length=100, null=True, verbose_name='آیکون متریال')),
                ('icon_svg', models.TextField(blank=True, null=True, verbose_name='آیکون svg')),
                ('color', models.CharField(choices=[('success', 'success'), ('danger', 'danger'), ('warning', 'warning'), ('primary', 'primary'), ('secondary', 'secondary'), ('info', 'info'), ('light', 'light'), ('dark', 'dark'), ('rose', 'rose'), ('DEFAULT', 'DEFAULT'), ('UNSET', 'UNSET')], default='UNSET', max_length=50, verbose_name='رنگ')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='عرض')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='ارتفاع')),
            ],
            options={
                'verbose_name': 'Icon',
                'verbose_name_plural': 'آیکون ها',
            },
        ),
        migrations.CreateModel(
            name='Jumbotron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='عنوان')),
                ('pretitle', models.CharField(blank=True, max_length=500, null=True, verbose_name='پیش عنوان')),
                ('posttitle', models.CharField(blank=True, max_length=500, null=True, verbose_name='پس عنوان')),
                ('short_description', tinymce.models.HTMLField(blank=True, max_length=1000, null=True, verbose_name='شرح کوتاه')),
                ('description', tinymce.models.HTMLField(blank=True, max_length=2000, null=True, verbose_name='شرح کامل')),
            ],
            options={
                'verbose_name': 'Jumbotron',
                'verbose_name_plural': 'Jumbotrons',
            },
        ),
        migrations.CreateModel(
            name='MainPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('آیکون سایت', 'آیکون سایت'), ('سایت', 'سایت'), ('سوالات', 'سوالات'), ('جستجو', 'جستجو'), ('ویدیو', 'ویدیو'), ('درباره ما', 'درباره ما'), ('سربرگ ارتباط با ما', 'سربرگ ارتباط با ما'), ('لودینگ', 'لودینگ'), ('لوگو', 'لوگو'), ('لوگوی بزرگ', 'لوگوی بزرگ'), ('لوگوی تیره', 'لوگوی تیره'), ('لوگوی روشن', 'لوگوی روشن'), ('سربرگ مقاله', 'سربرگ مقاله'), ('سربرگ پروژه', 'سربرگ پروژه'), ('سربرگ پیش فرض برای صفحات', 'سربرگ پیش فرض برای صفحات'), ('سربرگ درباره ما', 'سربرگ درباره ما'), ('سربرگ برچسب', 'سربرگ برچسب')], max_length=50, verbose_name='جای تصویر')),
                ('image_origin', models.ImageField(blank=True, null=True, upload_to='dashboard/images/MainPic/', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'MainPic',
                'verbose_name_plural': 'تصویر های اصلی سایت',
            },
        ),
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_home', models.BooleanField(default=False, verbose_name='نمایش در صفحه اصلی')),
                ('key', models.CharField(default='name', max_length=50, verbose_name='key name')),
                ('value', models.CharField(default='description', max_length=50, verbose_name='key value')),
                ('content', models.CharField(max_length=2000, verbose_name='content')),
            ],
            options={
                'verbose_name': 'MetaData',
                'verbose_name_plural': 'متا دیتا - کلمات کلیدی سئو',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('country', models.CharField(max_length=50, verbose_name='کشور')),
                ('city', models.CharField(max_length=50, verbose_name='شهر')),
                ('salary', models.IntegerField(verbose_name='حقوق')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
            },
        ),
        migrations.CreateModel(
            name='OurTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=100, verbose_name='سمت')),
                ('description', models.CharField(max_length=500, verbose_name='توضیحات')),
                ('priority', models.IntegerField(default=1000, verbose_name='ترتیب')),
                ('image_origin', models.ImageField(upload_to='dashboard/images/OurTeam/', verbose_name='تصویر')),
                ('header_image_origin', models.ImageField(blank=True, null=True, upload_to='dashboard/images/OurTeam/Header/', verbose_name='تصویر سربرگ')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.profile', verbose_name='پروفایل')),
            ],
            options={
                'verbose_name': 'OurTeam',
                'verbose_name_plural': 'تیم ما',
                'db_table': 'OurTeam',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OurWorkCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('priority', models.IntegerField(default=100, verbose_name='ترتیب')),
                ('image_header', models.ImageField(blank=True, null=True, upload_to='dashboard/images/OurWorkCategory/', verbose_name='تصویر سربرگ')),
            ],
            options={
                'verbose_name': 'دسته بندی  پروژه',
                'verbose_name_plural': 'دسته بندی  پروژه ها',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('short_description', tinymce.models.HTMLField(blank=True, max_length=200, null=True, verbose_name='شرح کوتاه')),
                ('description', tinymce.models.HTMLField(blank=True, max_length=2000, null=True, verbose_name='شرح کامل')),
                ('child_class', models.CharField(max_length=50, verbose_name='child_class')),
                ('app_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='app_name')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date_added')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.color')),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.icon')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('رنگ متن منوی سایت', 'رنگ متن منوی سایت'), ('تگ سرچ گوگل', 'تگ سرچ گوگل'), ('درباره ما کوتاه', 'درباره ما کوتاه'), ('درباره ما کامل', 'درباره ما کامل'), ('موبایل', 'موبایل'), ('لینک', 'لینک'), ('ایمیل', 'ایمیل'), ('فکس', 'فکس'), ('تلفن', 'تلفن'), ('موقعیت در گوگل مپ', 'موقعیت در گوگل مپ'), ('آدرس', 'آدرس'), ('شرح کوتاه', 'شرح کوتاه'), ('عنوان درباره ما', 'عنوان درباره ما'), ('عنوان', 'عنوان'), ('واحد پول', 'واحد پول'), ('پیش عنوان', 'پیش عنوان'), ('عنوان ویدیو', 'عنوان ویدیو'), ('لینک ویدیو', 'لینک ویدیو'), ('ارتباط با ما', 'ارتباط با ما'), ('کد پستی', 'کد پستی'), ('قوانین', 'قوانین'), ('عنوان تیم ما', 'عنوان تیم ما'), ('لینک تیم ما', 'لینک تیم ما'), ('پیام درخواست نامعتبر', 'پیام درخواست نامعتبر'), ('رنگ سربرگ کروم در موبایل', 'رنگ سربرگ کروم در موبایل')], max_length=50, verbose_name='نام')),
                ('value', models.CharField(max_length=10000, verbose_name='مقدار')),
            ],
            options={
                'verbose_name': 'Parameter',
                'verbose_name_plural': 'پارامتر ها',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('خواف', 'خواف'), ('نشتیفان', 'نشتیفان'), ('سنگان', 'سنگان'), ('قاسم آباد', 'قاسم آباد'), ('تایباد', 'تایباد'), ('تربت جام', 'تربت جام'), ('فریمان', 'فریمان'), ('مشهد', 'مشهد'), ('تهران', 'تهران'), ('تربت حیدریه', 'تربت حیدریه')], default='خواف', max_length=50, verbose_name='name')),
                ('priority', models.IntegerField(default=100, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'منطقه ها',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(verbose_name='priority')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('subtitle', models.CharField(blank=True, max_length=50, null=True, verbose_name='subtitle')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='description')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('duration', models.CharField(blank=True, max_length=50, null=True, verbose_name='مدت زمان')),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'رزومه',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.page')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'مقالات',
            },
            bases=('dashboard.page',),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('icon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.icon')),
                ('file', models.FileField(blank=True, null=True, upload_to='dashboard/Document', verbose_name='فایل ضمیمه')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.profile', verbose_name='پروفایل')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'اسناد',
            },
            bases=('dashboard.icon',),
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.page')),
            ],
            options={
                'verbose_name': 'OurService',
                'verbose_name_plural': 'خدمات و سرویس ها',
            },
            bases=('dashboard.page',),
        ),
        migrations.CreateModel(
            name='GalleryAlbum',
            fields=[
                ('jumbotron_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.jumbotron')),
                ('image_origin', models.ImageField(blank=True, null=True, upload_to='dashboard/images/Gallery/Album/', verbose_name='Big Image 345*970 ')),
                ('for_home', models.BooleanField(default=False, verbose_name='Show on homepage')),
                ('archive', models.BooleanField(default=False, verbose_name='Archive?')),
                ('priority', models.IntegerField(default=100, verbose_name='Priority')),
                ('thumbnail_origin', models.ImageField(blank=True, null=True, upload_to='dashboard/images/Gallery/Album/Thumbnail/', verbose_name='Thumbnail Image')),
            ],
            options={
                'verbose_name': 'GalleryAlbum',
                'verbose_name_plural': 'آلبوم های تصاویر',
            },
            bases=('dashboard.jumbotron',),
        ),
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('jumbotron_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.jumbotron')),
                ('image_origin', models.ImageField(upload_to='dashboard/images/Gallery/Photo/', verbose_name='Big Image 345*970 ')),
                ('for_home', models.BooleanField(default=False, verbose_name='Show on homepage')),
                ('archive', models.BooleanField(default=False, verbose_name='Archive?')),
                ('priority', models.IntegerField(default=100, verbose_name='Priority')),
                ('thumbnail_origin', models.ImageField(blank=True, null=True, upload_to='dashboard/images/Gallery/Photo/Thumbnail/', verbose_name='Thumbnail Image')),
            ],
            options={
                'verbose_name': 'GalleryPhoto',
                'verbose_name_plural': 'تصاویر',
            },
            bases=('dashboard.jumbotron',),
        ),
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('jumbotron_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.jumbotron')),
                ('image_banner', models.ImageField(upload_to='dashboard/images/Banner/', verbose_name='تصویر اسلایدر  1333*2000 ')),
                ('archive', models.BooleanField(default=False, verbose_name='بایگانی شود؟')),
                ('priority', models.IntegerField(default=100, verbose_name='ترتیب')),
                ('text_color', models.CharField(default='#fff', max_length=20, verbose_name='رنگ متن')),
                ('tag_number', models.IntegerField(default=100, verbose_name='عدد برچسب')),
                ('tag_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='متن برچسب')),
            ],
            options={
                'verbose_name': 'HomeSlider',
                'verbose_name_plural': 'اسلایدر های صفحه اصلی',
            },
            bases=('dashboard.jumbotron',),
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('icon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.icon')),
                ('for_home', models.BooleanField(default=False, verbose_name='نمایش در پایین صفحه سایت')),
                ('for_nav', models.BooleanField(default=False, verbose_name='نمایش در منوی بالای سایت')),
                ('priority', models.IntegerField(default=100, verbose_name='ترتیب')),
                ('url', models.CharField(default='#', max_length=2000, verbose_name='لینک')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'لینک ها',
            },
            bases=('dashboard.icon',),
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.page')),
            ],
            options={
                'verbose_name': 'Technology',
                'verbose_name_plural': 'تکنولوژی',
            },
            bases=('dashboard.page',),
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_home', models.BooleanField(default=False, verbose_name='نمایش در صفحه خانه')),
                ('image_origin', models.ImageField(blank=True, null=True, upload_to='dashboard/images/Testimonial/', verbose_name='تصویر')),
                ('title', models.CharField(max_length=2000, verbose_name='عنوان')),
                ('body', models.CharField(blank=True, max_length=2000, null=True, verbose_name='متن')),
                ('footer', models.CharField(max_length=200, verbose_name='پانوشت')),
                ('priority', models.IntegerField(default=100, verbose_name='ترتیب')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='authentication.profile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'گفته های مشتریان',
            },
        ),
        migrations.CreateModel(
            name='ResumeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('تجربه ها', 'تجربه ها'), ('آموزش ها', 'آموزش ها'), ('مهارت ها', 'مهارت ها'), ('علاقه ها', 'علاقه ها'), ('گواهینامه ها', 'گواهینامه ها'), ('جایزه ها', 'جایزه ها'), ('کار های انجام شده', 'کار های انجام شده')], default='آموزش ها', max_length=50, verbose_name='title')),
                ('priority', models.IntegerField(verbose_name='priority')),
                ('our_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.ourteam', verbose_name='our_team')),
                ('resumes', models.ManyToManyField(to='dashboard.Resume', verbose_name='resume')),
            ],
            options={
                'verbose_name': 'ResumeCategory',
                'verbose_name_plural': 'دسته بندی رزومه',
            },
        ),
        migrations.AddField(
            model_name='ourteam',
            name='resume_categories',
            field=models.ManyToManyField(blank=True, to='dashboard.ResumeCategory', verbose_name='ResumeCategories'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('body', models.CharField(blank=True, max_length=500, null=True, verbose_name='توضیحات')),
                ('url', models.CharField(blank=True, max_length=1100, null=True, verbose_name='url')),
                ('seen', models.BooleanField(default=False, verbose_name='دیده شد')),
                ('priority', models.IntegerField(default=1000, verbose_name='اولویت')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('date_seen', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ دیده شده')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.color')),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.icon')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.profile', verbose_name='پروفایل')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'اعلان ها',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.profile', verbose_name='توسط')),
            ],
            options={
                'verbose_name': 'Like',
                'verbose_name_plural': 'لایک های کاربران',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_home', models.BooleanField(default=False, verbose_name='نمایش در صفحه خانه')),
                ('priority', models.IntegerField(verbose_name='ترتیب')),
                ('question', models.CharField(max_length=200, verbose_name='سوال')),
                ('answer', models.CharField(max_length=5000, verbose_name='پاسخ')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.color')),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.icon')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'پرسش های متداول',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='نظر')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.profile', verbose_name='توسط')),
                ('replys', models.ManyToManyField(blank=True, to='dashboard.Comment', verbose_name='پاسخ ها')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'نظرات کاربران',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.color')),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.icon')),
                ('jumbotron', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.jumbotron')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
            },
        ),
        migrations.AddField(
            model_name='resume',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.galleryalbum', verbose_name='آلبوم'),
        ),
        migrations.AddField(
            model_name='resume',
            name='documents',
            field=models.ManyToManyField(blank=True, to='dashboard.Document', verbose_name='documents'),
        ),
        migrations.AddField(
            model_name='resume',
            name='links',
            field=models.ManyToManyField(blank=True, to='dashboard.Link', verbose_name='links'),
        ),
        migrations.CreateModel(
            name='OurWork',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.page')),
                ('location', models.CharField(blank=True, max_length=500, null=True, verbose_name='موقعیت در نقشه گوگل 400*400')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.ourworkcategory', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'OurWork',
                'verbose_name_plural': 'پروژه ها',
            },
            bases=('dashboard.page',),
        ),
        migrations.AddField(
            model_name='galleryalbum',
            name='photos',
            field=models.ManyToManyField(blank=True, to='dashboard.GalleryPhoto', verbose_name='Photos'),
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('link_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.link')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='authentication.profile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'SocialLink',
                'verbose_name_plural': 'شبکه اجتماعی',
            },
            bases=('dashboard.link',),
        ),
        migrations.AddField(
            model_name='ourteam',
            name='social_links',
            field=models.ManyToManyField(blank=True, to='dashboard.SocialLink', verbose_name='social_links'),
        ),
    ]
