# Generated by Django 3.1.2 on 2020-10-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='child_class',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='child_class'),
        ),
    ]
