# Generated by Django 3.1.2 on 2020-11-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='pages', to='dashboard.Comment', verbose_name='نطر ها'),
        ),
    ]
