# Generated by Django 3.1.2 on 2020-10-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_card_color_icon_jumbotron'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='icon',
            options={'verbose_name': 'Icon', 'verbose_name_plural': 'آیکون ها'},
        ),
        migrations.RemoveField(
            model_name='icon',
            name='icon',
        ),
        migrations.AddField(
            model_name='icon',
            name='color',
            field=models.CharField(choices=[('success', 'success'), ('danger', 'danger'), ('warning', 'warning'), ('primary', 'primary'), ('secondary', 'secondary'), ('info', 'info'), ('light', 'light'), ('dark', 'dark'), ('rose', 'rose'), ('', '')], default='primary', max_length=50, verbose_name='رنگ'),
        ),
        migrations.AddField(
            model_name='icon',
            name='height',
            field=models.IntegerField(default=128, verbose_name='ارتفاع'),
        ),
        migrations.AddField(
            model_name='icon',
            name='icon_fa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='آیکون فونت آسوم'),
        ),
        migrations.AddField(
            model_name='icon',
            name='icon_material',
            field=models.CharField(blank=True, choices=[('place', 'place'), ('construction', 'construction'), ('extension', 'extension'), ('engineering', 'engineering'), ('account_circle', 'account_circle'), ('add_shopping_cart', 'add_shopping_cart'), ('apartment', 'apartment'), ('alarm', 'alarm'), ('attach_file', 'attach_file'), ('attach_money', 'attach_money'), ('backup', 'backup'), ('build', 'build'), ('chat', 'chat'), ('dashboard', 'dashboard'), ('delete', 'delete'), ('description', 'description'), ('face', 'face'), ('favorite', 'favorite'), ('get_app', 'get_app'), ('help_outline', 'help_outline'), ('home', 'home'), ('important_devices', 'important_devices'), ('link', 'link'), ('local_shipping', 'local_shipping'), ('lock', 'lock'), ('mail', 'mail'), ('notification_important', 'notification_important'), ('psychology', 'psychology'), ('publish', 'publish'), ('reply', 'reply'), ('schedule', 'schedule'), ('send', 'send'), ('settings', 'settings'), ('share', 'share'), ('sync', 'sync'), ('vpn_key', 'vpn_key')], max_length=100, null=True, verbose_name='آیکون متریال'),
        ),
        migrations.AddField(
            model_name='icon',
            name='icon_svg',
            field=models.TextField(blank=True, null=True, verbose_name='آیکون svg'),
        ),
        migrations.AddField(
            model_name='icon',
            name='icon_title',
            field=models.CharField(default='icon 1', max_length=50, verbose_name='عنوان'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='icon',
            name='image_origin',
            field=models.ImageField(blank=True, null=True, upload_to='dashboard/images/OurService/', verbose_name='تصویر'),
        ),
        migrations.AddField(
            model_name='icon',
            name='width',
            field=models.IntegerField(default=128, verbose_name='عرض'),
        ),
        migrations.AlterModelTable(
            name='icon',
            table=None,
        ),
    ]
