# Generated by Django 3.1.2 on 2020-11-07 14:20

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_page_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallink',
            name='app_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='لینک شبکه های اجتماعی'),
        ),
        migrations.AlterField(
            model_name='icon',
            name='icon_material',
            field=models.CharField(blank=True, choices=[('account_circle', 'account_circle'), ('add_shopping_cart', 'add_shopping_cart'), ('apartment', 'apartment'), ('alarm', 'alarm'), ('attach_file', 'attach_file'), ('attach_money', 'attach_money'), ('backup', 'backup'), ('build', 'build'), ('card_travel', 'card_travel'), ('chat', 'chat'), ('construction', 'construction'), ('dashboard', 'dashboard'), ('delete', 'delete'), ('description', 'description'), ('emoji_objects', 'emoji_objects'), ('engineering', 'engineering'), ('extension', 'extension'), ('face', 'face'), ('facebook', 'facebook'), ('favorite', 'favorite'), ('fingerprint', 'fingerprint'), ('get_app', 'get_app'), ('help_outline', 'help_outline'), ('home', 'home'), ('important_devices', 'important_devices'), ('link', 'link'), ('linked_camera', 'linked_camera'), ('local_shipping', 'local_shipping'), ('lock', 'lock'), ('mail', 'mail'), ('movie_filter', 'movie_filter'), ('network_check', 'network_check'), ('notification_important', 'notification_important'), ('palette', 'palette'), ('phone', 'phone'), ('place', 'place'), ('psychology', 'psychology'), ('publish', 'publish'), ('reply', 'reply'), ('schedule', 'schedule'), ('school', 'school'), ('send', 'send'), ('settings', 'settings'), ('share', 'share'), ('sync', 'sync'), ('traffic', 'traffic'), ('two_wheeler', 'two_wheeler'), ('verified_user', 'verified_user'), ('vpn_key', 'vpn_key'), ('weekend', 'weekend')], max_length=100, null=True, verbose_name='آیکون متریال'),
        ),
        migrations.AlterField(
            model_name='page',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='page_for_comment', to='dashboard.Comment', verbose_name='نطر ها'),
        ),
        migrations.AlterField(
            model_name='page',
            name='description',
            field=tinymce.models.HTMLField(blank=True, max_length=100000, null=True, verbose_name='شرح کامل'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='name',
            field=models.CharField(choices=[('GOOGLE_API_KEY', 'GOOGLE_API_KEY'), ('GOOGLE_GPS_X', 'GOOGLE_GPS_X'), ('GOOGLE_GPS_Y', 'GOOGLE_GPS_Y'), ('درباره ما کامل', 'درباره ما کامل'), ('درباره ما کوتاه', 'درباره ما کوتاه'), ('عنوان درباره ما', 'عنوان درباره ما'), ('آدرس', 'آدرس'), ('واحد پول', 'واحد پول'), ('ارتباط با ما', 'ارتباط با ما'), ('پیام درخواست نامعتبر', 'پیام درخواست نامعتبر'), ('ایمیل', 'ایمیل'), ('فکس', 'فکس'), ('تگ سرچ گوگل', 'تگ سرچ گوگل'), ('موقعیت در گوگل مپ', 'موقعیت در گوگل مپ'), ('موبایل', 'موبایل'), ('رنگ زمینه منوی بالای سایت', 'رنگ زمینه منوی بالای سایت'), ('رنگ متن منوی بالای سایت', 'رنگ متن منوی بالای سایت'), ('لینک تیم ما', 'لینک تیم ما'), ('عنوان تیم ما', 'عنوان تیم ما'), ('کد پستی', 'کد پستی'), ('پیش عنوان', 'پیش عنوان'), ('شرح کوتاه', 'شرح کوتاه'), ('تلفن', 'تلفن'), ('قوانین', 'قوانین'), ('رنگ سربرگ کروم در موبایل', 'رنگ سربرگ کروم در موبایل'), ('عنوان', 'عنوان'), ('لینک', 'لینک'), ('لینک ویدیو', 'لینک ویدیو'), ('عنوان ویدیو', 'عنوان ویدیو')], max_length=50, verbose_name='نام'),
        ),
    ]
