# Generated by Django 3.1.2 on 2020-10-24 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20201024_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='color',
            field=models.CharField(blank=True, choices=[('success', 'success'), ('danger', 'danger'), ('warning', 'warning'), ('primary', 'primary'), ('secondary', 'secondary'), ('info', 'info'), ('light', 'light'), ('dark', 'dark'), ('rose', 'rose'), ('DEFAULT', 'DEFAULT'), ('UNSET', 'UNSET')], default='DEFAULT', max_length=50, null=True, verbose_name='color class'),
        ),
    ]
