# Generated by Django 3.1.2 on 2020-10-22 19:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profile_slogan'),
        ('dashboard', '0004_auto_20201022_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('icon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.icon')),
                ('file', models.FileField(blank=True, null=True, upload_to='dashboard/Document', verbose_name='فایل ضمیمه')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.profile', verbose_name='پروفایل')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'اسناد',
            },
            bases=('dashboard.icon',),
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.page')),
            ],
            options={
                'verbose_name': 'OurService',
                'verbose_name_plural': 'خدمات و سرویس ها',
            },
            bases=('dashboard.page',),
        ),
        migrations.CreateModel(
            name='GalleryAlbum',
            fields=[
                ('jumbotron_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.jumbotron')),
                ('image_origin', models.ImageField(blank=True, null=True, upload_to='dashboard/images/Gallery/Album/', verbose_name='Big Image 345*970 ')),
                ('for_home', models.BooleanField(default=False, verbose_name='Show on homepage')),
                ('archive', models.BooleanField(default=False, verbose_name='Archive?')),
                ('priority', models.IntegerField(default=100, verbose_name='Priority')),
                ('thumbnail_origin', models.ImageField(blank=True, null=True, upload_to='dashboard/images/Gallery/Album/Thumbnail/', verbose_name='Thumbnail Image')),
            ],
            options={
                'verbose_name': 'GalleryAlbum',
                'verbose_name_plural': 'آلبوم های تصاویر',
            },
            bases=('dashboard.jumbotron',),
        ),
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('jumbotron_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.jumbotron')),
                ('image_origin', models.ImageField(upload_to='dashboard/images/Gallery/Photo/', verbose_name='Big Image 345*970 ')),
                ('for_home', models.BooleanField(default=False, verbose_name='Show on homepage')),
                ('archive', models.BooleanField(default=False, verbose_name='Archive?')),
                ('priority', models.IntegerField(default=100, verbose_name='Priority')),
                ('thumbnail_origin', models.ImageField(blank=True, null=True, upload_to='dashboard/images/Gallery/Photo/Thumbnail/', verbose_name='Thumbnail Image')),
            ],
            options={
                'verbose_name': 'GalleryPhoto',
                'verbose_name_plural': 'تصاویر',
            },
            bases=('dashboard.jumbotron',),
        ),
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('jumbotron_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.jumbotron')),
                ('image_banner', models.ImageField(upload_to='dashboard/images/Banner/', verbose_name='تصویر اسلایدر  1333*2000 ')),
                ('archive', models.BooleanField(default=False, verbose_name='بایگانی شود؟')),
                ('priority', models.IntegerField(default=100, verbose_name='ترتیب')),
                ('text_color', models.CharField(default='#fff', max_length=20, verbose_name='رنگ متن')),
                ('tag_number', models.IntegerField(default=100, verbose_name='عدد برچسب')),
                ('tag_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='متن برچسب')),
            ],
            options={
                'verbose_name': 'HomeSlider',
                'verbose_name_plural': 'اسلایدر های صفحه اصلی',
            },
            bases=('dashboard.jumbotron',),
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('icon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.icon')),
                ('for_home', models.BooleanField(default=False, verbose_name='نمایش در پایین صفحه سایت')),
                ('for_nav', models.BooleanField(default=False, verbose_name='نمایش در منوی بالای سایت')),
                ('priority', models.IntegerField(default=100, verbose_name='ترتیب')),
                ('url', models.CharField(default='#', max_length=2000, verbose_name='لینک')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='authentication.profile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'لینک ها',
            },
            bases=('dashboard.icon',),
        ),
        migrations.CreateModel(
            name='NotificationTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('country', models.CharField(max_length=50, verbose_name='کشور')),
                ('city', models.CharField(max_length=50, verbose_name='شهر')),
                ('salary', models.IntegerField(verbose_name='حقوق')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
            },
        ),
        migrations.CreateModel(
            name='OurTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=100, verbose_name='سمت')),
                ('description', models.CharField(max_length=500, verbose_name='توضیحات')),
                ('priority', models.IntegerField(default=1000, verbose_name='ترتیب')),
                ('image_origin', models.ImageField(upload_to='dashboard/images/OurTeam/', verbose_name='تصویر')),
                ('header_image_origin', models.ImageField(blank=True, null=True, upload_to='dashboard/images/OurTeam/Header/', verbose_name='تصویر سربرگ')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.profile', verbose_name='پروفایل')),
            ],
            options={
                'verbose_name': 'OurTeam',
                'verbose_name_plural': 'تیم ما',
                'db_table': 'OurTeam',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OurWorkCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('priority', models.IntegerField(default=100, verbose_name='ترتیب')),
                ('image_header', models.ImageField(blank=True, null=True, upload_to='dashboard/images/OurWorkCategory/', verbose_name='تصویر سربرگ')),
            ],
            options={
                'verbose_name': 'دسته بندی  پروژه',
                'verbose_name_plural': 'دسته بندی  پروژه ها',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('خواف', 'خواف'), ('نشتیفان', 'نشتیفان'), ('سنگان', 'سنگان'), ('قاسم آباد', 'قاسم آباد'), ('تایباد', 'تایباد'), ('تربت جام', 'تربت جام'), ('فریمان', 'فریمان'), ('مشهد', 'مشهد'), ('تهران', 'تهران'), ('تربت حیدریه', 'تربت حیدریه')], default='خواف', max_length=50, verbose_name='name')),
                ('priority', models.IntegerField(default=100, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'منطقه ها',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(verbose_name='priority')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('subtitle', models.CharField(blank=True, max_length=50, null=True, verbose_name='subtitle')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='description')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('duration', models.CharField(blank=True, max_length=50, null=True, verbose_name='مدت زمان')),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.galleryalbum', verbose_name='آلبوم')),
                ('documents', models.ManyToManyField(blank=True, to='dashboard.Document', verbose_name='documents')),
                ('links', models.ManyToManyField(blank=True, to='dashboard.Link', verbose_name='links')),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'رزومه',
            },
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Notification', 'verbose_name_plural': 'اعلان ها'},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='city',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='country',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='name',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='salary',
        ),
        migrations.AddField(
            model_name='notification',
            name='body',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='notification',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.color'),
        ),
        migrations.AddField(
            model_name='notification',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='date_seen',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ دیده شده'),
        ),
        migrations.AddField(
            model_name='notification',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.icon'),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.IntegerField(default=1000, verbose_name='اولویت'),
        ),
        migrations.AddField(
            model_name='notification',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.profile', verbose_name='پروفایل'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='seen',
            field=models.BooleanField(default=False, verbose_name='دیده شد'),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='..', max_length=50, verbose_name='عنوان'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='url',
            field=models.CharField(blank=True, max_length=1100, null=True, verbose_name='url'),
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('link_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.link')),
            ],
            options={
                'verbose_name': 'SocialLink',
                'verbose_name_plural': 'شبکه اجتماعی',
            },
            bases=('dashboard.link',),
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_home', models.BooleanField(default=False, verbose_name='نمایش در صفحه خانه')),
                ('image_origin', models.ImageField(blank=True, null=True, upload_to='dashboard/images/Testimonial/', verbose_name='تصویر')),
                ('title', models.CharField(max_length=2000, verbose_name='عنوان')),
                ('body', models.CharField(blank=True, max_length=2000, null=True, verbose_name='متن')),
                ('footer', models.CharField(max_length=200, verbose_name='پانوشت')),
                ('priority', models.IntegerField(default=100, verbose_name='ترتیب')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='authentication.profile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'گفته های مشتریان',
            },
        ),
        migrations.CreateModel(
            name='ResumeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('تجربه ها', 'تجربه ها'), ('آموزش ها', 'آموزش ها'), ('مهارت ها', 'مهارت ها'), ('علاقه ها', 'علاقه ها'), ('گواهینامه ها', 'گواهینامه ها'), ('جایزه ها', 'جایزه ها'), ('کار های انجام شده', 'کار های انجام شده')], default='آموزش ها', max_length=50, verbose_name='title')),
                ('priority', models.IntegerField(verbose_name='priority')),
                ('our_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.ourteam', verbose_name='our_team')),
                ('resumes', models.ManyToManyField(to='dashboard.Resume', verbose_name='resume')),
            ],
            options={
                'verbose_name': 'ResumeCategory',
                'verbose_name_plural': 'دسته بندی رزومه',
            },
        ),
        migrations.CreateModel(
            name='OurWork',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.page')),
                ('location', models.CharField(blank=True, max_length=500, null=True, verbose_name='موقعیت در نقشه گوگل 400*400')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.ourworkcategory', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'OurWork',
                'verbose_name_plural': 'پروژه ها',
            },
            bases=('dashboard.page',),
        ),
        migrations.AddField(
            model_name='ourteam',
            name='resume_categories',
            field=models.ManyToManyField(blank=True, to='dashboard.ResumeCategory', verbose_name='ResumeCategories'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.profile', verbose_name='توسط')),
            ],
            options={
                'verbose_name': 'Like',
                'verbose_name_plural': 'لایک های کاربران',
            },
        ),
        migrations.AddField(
            model_name='galleryalbum',
            name='photos',
            field=models.ManyToManyField(blank=True, to='dashboard.GalleryPhoto', verbose_name='Photos'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='نظر')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.profile', verbose_name='توسط')),
                ('replys', models.ManyToManyField(blank=True, to='dashboard.Comment', verbose_name='پاسخ ها')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'نظرات کاربران',
            },
        ),
        migrations.AddField(
            model_name='ourteam',
            name='social_links',
            field=models.ManyToManyField(blank=True, to='dashboard.SocialLink', verbose_name='social_links'),
        ),
    ]
