# Generated by Django 3.1.2 on 2020-11-13 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20201113_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='category'),
        ),
    ]
