# Generated by Django 3.1.2 on 2020-10-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20201024_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='priority',
            field=models.IntegerField(default=100, verbose_name='ترتیب'),
        ),
    ]
