# Generated by Django 3.1.2 on 2020-10-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_page_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='for_home',
            field=models.BooleanField(default=False, verbose_name='در صفحه اصلی نمایش داده شود؟'),
        ),
    ]
