# Generated by Django 3.1.2 on 2020-10-22 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_icon_icon_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color_class',
            field=models.CharField(blank=True, choices=[('success', 'success'), ('danger', 'danger'), ('warning', 'warning'), ('primary', 'primary'), ('secondary', 'secondary'), ('info', 'info'), ('light', 'light'), ('dark', 'dark'), ('rose', 'rose'), ('DEFAULT', 'DEFAULT'), ('UNSET', 'UNSET')], default='DEFAULT', max_length=50, null=True, verbose_name='color class'),
        ),
        migrations.AlterField(
            model_name='icon',
            name='color',
            field=models.CharField(choices=[('success', 'success'), ('danger', 'danger'), ('warning', 'warning'), ('primary', 'primary'), ('secondary', 'secondary'), ('info', 'info'), ('light', 'light'), ('dark', 'dark'), ('rose', 'rose'), ('DEFAULT', 'DEFAULT'), ('UNSET', 'UNSET')], default='UNSET', max_length=50, verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='icon',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='ارتفاع'),
        ),
        migrations.AlterField(
            model_name='icon',
            name='width',
            field=models.IntegerField(blank=True, null=True, verbose_name='عرض'),
        ),
    ]
