# Generated by Django 3.1.2 on 2020-10-24 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_page_for_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='header_image_origin',
            field=models.ImageField(blank=True, null=True, upload_to='dashboard/images/Page/Header/', verbose_name='تصویر سربرگ'),
        ),
        migrations.AddField(
            model_name='page',
            name='image_origin',
            field=models.ImageField(blank=True, null=True, upload_to='dashboard/images/Page/Main/', verbose_name='تصویر'),
        ),
        migrations.AddField(
            model_name='page',
            name='thumbnail_origin',
            field=models.ImageField(blank=True, null=True, upload_to='dashboard/images/Page/Thumbnail/', verbose_name='تصویر کوچک'),
        ),
    ]
