# Generated by Django 3.1.2 on 2020-10-23 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_profile_image_header_origin'),
        ('dashboard', '0007_auto_20201022_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='profile',
        ),
        migrations.AddField(
            model_name='sociallink',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='authentication.profile', verbose_name='profile'),
        ),
    ]
