# Generated by Django 3.1.2 on 2020-10-24 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('dashboard', '0008_auto_20201024_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.profile', verbose_name='profile'),
        ),
    ]
