# Generated by Django 3.1.2 on 2020-10-25 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20201025_2022'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GalleryPhoto2',
            new_name='GalleryPhoto',
        ),
    ]
