# Generated by Django 3.1.2 on 2020-10-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20201025_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryalbum',
            name='photos',
            field=models.ManyToManyField(blank=True, to='dashboard.GalleryPhoto', verbose_name='Photos'),
        ),
        migrations.AddField(
            model_name='page',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='pages', to='dashboard.GalleryPhoto', verbose_name='تصویر ها'),
        ),
    ]
