# Generated by Django 3.1.2 on 2020-10-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20201025_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryphoto',
            name='image_description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='شرح تصویر'),
        ),
        migrations.AddField(
            model_name='galleryphoto',
            name='image_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان تصویر'),
        ),
    ]
