# Generated by Django 3.1.2 on 2020-10-25 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_auto_20201025_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryphoto',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='موقعیت مکانی تصویر'),
        ),
    ]
