# Generated by Django 3.1.2 on 2020-10-25 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_galleryphoto_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='related_pages',
            field=models.ManyToManyField(blank=True, to='dashboard.Page', verbose_name='صفحه های مرتبط'),
        ),
    ]
