# Generated by Django 3.1.2 on 2020-10-25 22:03

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_page_related_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='description',
            field=tinymce.models.HTMLField(blank=True, max_length=10000, null=True, verbose_name='شرح کامل'),
        ),
        migrations.AlterField(
            model_name='page',
            name='short_description',
            field=tinymce.models.HTMLField(blank=True, max_length=1000, null=True, verbose_name='شرح کوتاه'),
        ),
    ]
