# Generated by Django 3.1.2 on 2020-10-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_auto_20201025_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='priority',
            field=models.IntegerField(default=100, verbose_name='ترتیب'),
        ),
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(default='doc1', max_length=200, verbose_name='عنوان'),
            preserve_default=False,
        ),
    ]
