# Generated by Django 3.1.2 on 2020-10-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_auto_20201027_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='pages', to='dashboard.Document', verbose_name='دانلود ها'),
        ),
    ]
