# Generated by Django 3.1.2 on 2020-10-29 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('dashboard', '0026_auto_20201027_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='profile_adder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.profile', verbose_name='پروفایل'),
            preserve_default=False,
        ),
    ]
