# Generated by Django 3.1.2 on 2020-10-30 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('dashboard', '0028_auto_20201029_2244'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationTemp',
        ),
        migrations.AddField(
            model_name='galleryphoto',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.profile', verbose_name='پروفایل'),
        ),
    ]
