# Generated by Django 3.1.2 on 2020-10-30 01:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_auto_20201030_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryphoto',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='افزوده شده در'),
            preserve_default=False,
        ),
    ]
