# Generated by Django 3.1.2 on 2020-10-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_galleryphoto_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='icon_material',
            field=models.CharField(blank=True, choices=[('engineering', 'engineering'), ('account_circle', 'account_circle'), ('add_shopping_cart', 'add_shopping_cart'), ('apartment', 'apartment'), ('alarm', 'alarm'), ('attach_file', 'attach_file'), ('attach_money', 'attach_money'), ('backup', 'backup'), ('build', 'build'), ('card_travel', 'card_travel'), ('chat', 'chat'), ('construction', 'construction'), ('dashboard', 'dashboard'), ('delete', 'delete'), ('description', 'description'), ('extension', 'extension'), ('face', 'face'), ('favorite', 'favorite'), ('fingerprint', 'fingerprint'), ('get_app', 'get_app'), ('help_outline', 'help_outline'), ('home', 'home'), ('important_devices', 'important_devices'), ('link', 'link'), ('local_shipping', 'local_shipping'), ('lock', 'lock'), ('mail', 'mail'), ('notification_important', 'notification_important'), ('place', 'place'), ('psychology', 'psychology'), ('publish', 'publish'), ('reply', 'reply'), ('schedule', 'schedule'), ('send', 'send'), ('settings', 'settings'), ('share', 'share'), ('sync', 'sync'), ('verified_user', 'verified_user'), ('vpn_key', 'vpn_key'), ('weekend', 'weekend')], max_length=100, null=True, verbose_name='آیکون متریال'),
        ),
    ]
