# Generated by Django 3.1.2 on 2020-11-04 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_auto_20201104_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumecategory',
            name='resumes',
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
