# Generated by Django 3.1.2 on 2020-11-04 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_auto_20201104_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.page')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='start_date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='end_date')),
                ('duration', models.CharField(blank=True, max_length=50, null=True, verbose_name='مدت زمان')),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'رزومه',
            },
            bases=('dashboard.page',),
        ),
        migrations.AddField(
            model_name='resumecategory',
            name='resumes',
            field=models.ManyToManyField(to='dashboard.Resume', verbose_name='resume'),
        ),
    ]
