# Generated by Django 3.1.2 on 2020-11-04 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_auto_20201104_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumecategory',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.icon', verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='resumecategory',
            name='priority',
            field=models.IntegerField(default=100, verbose_name='priority'),
        ),
    ]
