# Generated by Django 3.1.2 on 2020-11-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_auto_20201104_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام رنگ')),
                ('color', models.CharField(max_length=50, verbose_name='کد رنگ')),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'رنگ ها',
            },
        ),
    ]
