# Generated by Django 3.1.2 on 2020-11-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourteam',
            name='header_image_origin',
        ),
        migrations.RemoveField(
            model_name='ourteam',
            name='image_origin',
        ),
        migrations.AlterField(
            model_name='page',
            name='short_description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='شرح کوتاه'),
        ),
    ]
