# Generated by Django 3.1.2 on 2020-10-23 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0008_auto_20201023_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('short_description', models.CharField(max_length=50, verbose_name='short_description')),
                ('description', models.CharField(max_length=50, verbose_name='description')),
                ('color_class', models.CharField(blank=True, choices=[('success', 'success'), ('danger', 'danger'), ('warning', 'warning'), ('primary', 'primary'), ('secondary', 'secondary'), ('info', 'info'), ('light', 'light'), ('dark', 'dark'), ('rose', 'rose'), ('DEFAULT', 'DEFAULT'), ('UNSET', 'UNSET')], default='DEFAULT', max_length=50, null=True, verbose_name='color class')),
                ('child_class', models.CharField(max_length=200, verbose_name='title')),
                ('app_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='app_name')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projectpages', to='dashboard.color', verbose_name='color')),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projectpages', to='dashboard.icon', verbose_name='icon')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projectmanager.page')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
            bases=('projectmanager.page',),
        ),
    ]
