# Generated by Django 3.1.2 on 2020-10-23 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.IntegerField(default=1, verbose_name='priority'),
            preserve_default=False,
        ),
    ]
