# Generated by Django 3.1.2 on 2020-11-08 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20201107_1439'),
        ('projectmanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('نگهبان', 'نگهبان'), ('مدیر', 'مدیر'), ('فنی', 'فنی'), ('تایید نشده', 'تایید نشده'), ('حسابدار', 'حسابدار'), ('صندوقدار', 'صندوقدار')], default='تایید نشده', max_length=50, verbose_name='نقش')),
                ('degree', models.CharField(choices=[('دیپلم', 'دیپلم'), ('کاردانی', 'کاردانی'), ('کارشناسی', 'کارشناسی'), ('کارشناسی ارشد', 'کارشناسی ارشد'), ('دکتری', 'دکتری')], default='کارشناسی', max_length=50, verbose_name='مدرک')),
                ('major', models.CharField(blank=True, max_length=50, null=True, verbose_name='رشته تحصیلی')),
                ('introducer', models.CharField(blank=True, max_length=50, null=True, verbose_name='معرف')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_set_m', to='authentication.profile', verbose_name='profile')),
                ('work_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='projectmanager.organizationunit', verbose_name='work_unit')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees - کارکنان',
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('managerpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projectmanager.managerpage')),
                ('status', models.CharField(choices=[('DEFAULT', 'DEFAULT'), ('در جریان', 'در جریان'), ('انجام شده', 'انجام شده'), ('متوقف شده', 'متوقف شده'), ('رد شده', 'رد شده')], default='DEFAULT', max_length=50, verbose_name='status')),
                ('assign_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projectmanager.employee', verbose_name='کاربر مربوط')),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments - تکلیف ها',
            },
            bases=('projectmanager.managerpage',),
        ),
    ]
