# Generated by Django 3.1.2 on 2020-10-23 22:21

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0002_project_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date_added'),
        ),
        migrations.AlterField(
            model_name='page',
            name='child_class',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='child_class'),
        ),
        migrations.AlterField(
            model_name='page',
            name='description',
            field=tinymce.models.HTMLField(blank=True, max_length=2000, null=True, verbose_name='شرح کامل'),
        ),
        migrations.AlterField(
            model_name='page',
            name='short_description',
            field=tinymce.models.HTMLField(blank=True, max_length=1000, null=True, verbose_name='شرح کوتاه'),
        ),
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.IntegerField(default=100, verbose_name='priority'),
        ),
    ]
