# Generated by Django 3.1.2 on 2020-10-24 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0002_managerpage_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='priority',
            new_name='priority2',
        ),
    ]
