# Generated by Django 3.1.2 on 2020-11-10 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0003_auto_20201110_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='project_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_assignments', to='projectmanager.project', verbose_name='پروژه مربوط'),
        ),
    ]
