# Generated by Django 3.1.2 on 2020-10-23 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0003_auto_20201023_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='app_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='app_name'),
        ),
        migrations.AlterField(
            model_name='page',
            name='child_class',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='child_class'),
        ),
    ]
