# Generated by Django 3.1.2 on 2020-11-11 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20201108_1904'),
        ('projectmanager', '0005_auto_20201111_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialbrand',
            name='managerpage_ptr',
        ),
        migrations.RemoveField(
            model_name='materialcategory',
            name='managerpage_ptr',
        ),
        migrations.RemoveField(
            model_name='materialinstock',
            name='material_object',
        ),
        migrations.RemoveField(
            model_name='materialinstock',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='materialobject',
            name='material',
        ),
        migrations.RemoveField(
            model_name='materialpackage',
            name='material_objects',
        ),
        migrations.RemoveField(
            model_name='materialwarehouse',
            name='managerpage_ptr',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='MaterialBrand',
        ),
        migrations.DeleteModel(
            name='MaterialCategory',
        ),
        migrations.DeleteModel(
            name='MaterialInStock',
        ),
        migrations.DeleteModel(
            name='MaterialObject',
        ),
        migrations.DeleteModel(
            name='MaterialPackage',
        ),
        migrations.DeleteModel(
            name='MaterialWareHouse',
        ),
    ]
