# Generated by Django 3.1.2 on 2020-10-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0005_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='events',
            field=models.ManyToManyField(blank=True, to='projectmanager.Event', verbose_name='رویداد ها'),
        ),
    ]
