# Generated by Django 3.1.2 on 2020-11-12 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20201107_1439'),
        ('projectmanager', '0007_auto_20201111_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='تعداد')),
                ('description', models.CharField(default='', max_length=50, verbose_name='توضیحات')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درخواست')),
                ('date_delivered', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ درخواست')),
                ('status', models.CharField(choices=[('DEFAULT', 'DEFAULT'), ('تحویل شده', 'تحویل شده'), ('در حال بررسی', 'درحال بررسی'), ('رد شده', 'ردشده'), ('پذیرفته شده', 'پذیرفته شده'), ('درحال خرید', 'درحال خرید')], default='DEFAULT', max_length=50, verbose_name='وضعیت')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projectmanager.material', verbose_name='متریال')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.profile', verbose_name='تحویل گیرنده')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projectmanager.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'MaterialRequest',
                'verbose_name_plural': 'درخواست های متریال',
            },
        ),
    ]
