# Generated by Django 3.1.2 on 2020-10-27 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0007_organiazationunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('managerpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projectmanager.managerpage')),
            ],
            options={
                'verbose_name': 'Contractor',
                'verbose_name_plural': 'Contractors',
            },
            bases=('projectmanager.managerpage',),
        ),
    ]
