# Generated by Django 3.1.2 on 2020-11-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0008_materialrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialrequest',
            name='description',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='توضیحات'),
        ),
    ]
