# Generated by Django 3.1.2 on 2020-10-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0008_contractor'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contractors',
            field=models.ManyToManyField(blank=True, to='projectmanager.Contractor', verbose_name='پیمانکار ها'),
        ),
        migrations.AddField(
            model_name='project',
            name='organiazation_units',
            field=models.ManyToManyField(blank=True, to='projectmanager.OrganiazationUnit', verbose_name='واحد های سازمانی'),
        ),
    ]
