# Generated by Django 3.1.2 on 2020-10-29 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0009_auto_20201027_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.TextField(blank=True, null=True, verbose_name='موقعیت در نقشه گوگل مپ'),
        ),
    ]
