# Generated by Django 3.1.2 on 2020-11-12 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20201107_1439'),
        ('projectmanager', '0009_auto_20201112_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialRequestSignature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date_added')),
                ('description', models.CharField(max_length=200, verbose_name='description')),
                ('status', models.CharField(choices=[('DEFAULT', 'DEFAULT'), ('تایید شد', 'تایید شد'), ('رد شد', 'رد شد')], default='DEFAULT', max_length=200, verbose_name='status')),
                ('materialrequest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projectmanager.materialrequest', verbose_name='درخواست')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.profile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'MaterialRequestSignature',
                'verbose_name_plural': 'امضا ها',
            },
        ),
    ]
