# Generated by Django 3.1.2 on 2020-10-30 15:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0010_project_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 30, 15, 28, 4, 230032), verbose_name='event_date'),
            preserve_default=False,
        ),
    ]
