# Generated by Django 3.1.2 on 2020-10-30 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0011_event_event_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveDocument',
            fields=[
                ('managerpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projectmanager.managerpage')),
            ],
            options={
                'verbose_name': 'ArchiveDocument',
                'verbose_name_plural': 'اسناد آرشیوی',
            },
            bases=('projectmanager.managerpage',),
        ),
    ]
