# Generated by Django 3.1.2 on 2020-10-31 00:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0012_archivedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2020, 10, 31, 0, 25, 18, 108202), verbose_name='پایان'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='percent',
            field=models.IntegerField(default=0, verbose_name='درصد پیشرفت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2020, 10, 31, 0, 25, 47, 322679), verbose_name='شروع'),
            preserve_default=False,
        ),
    ]
