# Generated by Django 3.1.2 on 2020-10-31 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0014_auto_20201031_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='percent',
            field=models.IntegerField(default=0, verbose_name='درصد پیشرفت'),
        ),
    ]
