# Generated by Django 3.1.2 on 2020-11-04 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_auto_20201030_1900'),
        ('authentication', '0001_initial'),
        ('projectmanager', '0016_auto_20201031_1707'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrganiazationUnit',
            new_name='OrganizationUnit',
        ),
        migrations.AlterModelOptions(
            name='organizationunit',
            options={'verbose_name': 'OrganizationUnit', 'verbose_name_plural': 'OrganizationUnits'},
        ),
    ]
