# Generated by Django 3.1.2 on 2020-11-04 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0017_auto_20201104_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='organiazation_units',
            new_name='organization_units',
        ),
    ]
