# Generated by Django 3.1.2 on 2020-10-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slogan',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='جمله کوتاه'),
        ),
    ]
