# Generated by Django 3.1.2 on 2020-10-22 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profile_slogan'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image_header_origin',
            field=models.ImageField(blank=True, max_length=1200, null=True, upload_to='authentication/images/Profile/header/', verbose_name='تصویر سربرگ'),
        ),
    ]
