# Generated by Django 3.1.2 on 2020-11-14 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leopusher', '0002_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sender',
            new_name='profile',
        ),
    ]
